// <auto-generated />
using Academy_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy_2.Migrations
{
    [DbContext(typeof(Academy_2Context))]
    partial class Academy_2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academy_2.Components.Models.Direction", b =>
                {
                    b.Property<byte>("direction_id")
                        .HasColumnType("tinyint");

                    b.Property<string>("direction_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("direction_id");

                    b.ToTable("Direction");
                });
#pragma warning restore 612, 618
        }
    }
}
