// <auto-generated />
using System;
using HW_Academy_CRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW_Academy_CRUD.Migrations
{
    [DbContext(typeof(Pd321Context))]
    [Migration("20260324134111_mssql_migration_996")]
    partial class mssql_migration_996
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompleteDiscipline", b =>
                {
                    b.Property<int>("Group")
                        .HasColumnType("int")
                        .HasColumnName("group");

                    b.Property<short>("Discipline")
                        .HasColumnType("smallint")
                        .HasColumnName("discipline");

                    b.HasKey("Group", "Discipline");

                    b.HasIndex("Discipline");

                    b.ToTable("CompleteDisciplines", (string)null);
                });

            modelBuilder.Entity("DependentDiscipline", b =>
                {
                    b.Property<short>("Discipline")
                        .HasColumnType("smallint")
                        .HasColumnName("discipline");

                    b.Property<short>("DependentDiscipline1")
                        .HasColumnType("smallint")
                        .HasColumnName("dependent_discipline");

                    b.HasKey("Discipline", "DependentDiscipline1");

                    b.HasIndex("DependentDiscipline1");

                    b.ToTable("DependentDisciplines", (string)null);
                });

            modelBuilder.Entity("DisciplinesDirectionsRelation", b =>
                {
                    b.Property<byte>("Direction")
                        .HasColumnType("tinyint")
                        .HasColumnName("direction");

                    b.Property<short>("Discipline")
                        .HasColumnType("smallint")
                        .HasColumnName("discipline");

                    b.HasKey("Direction", "Discipline");

                    b.HasIndex("Discipline");

                    b.ToTable("DisciplinesDirectionsRelation", (string)null);
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Attendance", b =>
                {
                    b.Property<int>("Student")
                        .HasColumnType("int")
                        .HasColumnName("student");

                    b.Property<long>("Lesson")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson");

                    b.Property<bool>("Present")
                        .HasColumnType("bit")
                        .HasColumnName("present");

                    b.HasKey("Student", "Lesson");

                    b.HasIndex("Lesson");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.DaysOff", b =>
                {
                    b.Property<short>("DayoffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("dayoff_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DayoffId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<byte>("Holiday")
                        .HasColumnType("tinyint")
                        .HasColumnName("holiday");

                    b.HasKey("DayoffId")
                        .HasName("PK__DaysOFF__6603CDDA1D5C0E94");

                    b.HasIndex("Holiday");

                    b.ToTable("DaysOFF", (string)null);
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Direction", b =>
                {
                    b.Property<byte>("DirectionId")
                        .HasColumnType("tinyint")
                        .HasColumnName("direction_id");

                    b.Property<string>("DirectionName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("direction_name");

                    b.HasKey("DirectionId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Discipline", b =>
                {
                    b.Property<short>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("discipline_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DisciplineId"));

                    b.Property<string>("DisciplineName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("discipline_name");

                    b.Property<byte>("NumberOfLessons")
                        .HasColumnType("tinyint")
                        .HasColumnName("number_of_lessons");

                    b.HasKey("DisciplineId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Exam", b =>
                {
                    b.Property<int>("Student")
                        .HasColumnType("int")
                        .HasColumnName("student");

                    b.Property<short>("Discipline")
                        .HasColumnType("smallint")
                        .HasColumnName("discipline");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<byte?>("Grade")
                        .HasColumnType("tinyint")
                        .HasColumnName("grade");

                    b.HasKey("Student", "Discipline");

                    b.HasIndex("Discipline");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Grade", b =>
                {
                    b.Property<int>("Student")
                        .HasColumnType("int")
                        .HasColumnName("student");

                    b.Property<long>("Lesson")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson");

                    b.Property<byte?>("Grade1")
                        .HasColumnType("tinyint")
                        .HasColumnName("grade_1");

                    b.Property<byte?>("Grade2")
                        .HasColumnType("tinyint")
                        .HasColumnName("grade_2");

                    b.HasKey("Student", "Lesson")
                        .HasName("PK_Grades_1");

                    b.HasIndex("Lesson");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<byte?>("Direction")
                        .HasColumnType("tinyint")
                        .HasColumnName("direction");

                    b.Property<string>("GroupName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("group_name")
                        .IsFixedLength();

                    b.Property<byte?>("LearningDays")
                        .HasColumnType("tinyint")
                        .HasColumnName("learning_days");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("GroupId");

                    b.HasIndex("Direction");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Holiday", b =>
                {
                    b.Property<byte>("HolidayId")
                        .HasColumnType("tinyint")
                        .HasColumnName("holiday_id");

                    b.Property<byte>("Duration")
                        .HasColumnType("tinyint")
                        .HasColumnName("duration");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("holiday_name");

                    b.Property<byte?>("StartDay")
                        .HasColumnType("tinyint")
                        .HasColumnName("start_day");

                    b.Property<byte?>("StartMonth")
                        .HasColumnType("tinyint")
                        .HasColumnName("start_month");

                    b.HasKey("HolidayId")
                        .HasName("PK__Holidays__253884EA4E779255");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Schedule", b =>
                {
                    b.Property<long>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LessonId"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<short>("Discipline")
                        .HasColumnType("smallint")
                        .HasColumnName("discipline");

                    b.Property<int>("Group")
                        .HasColumnType("int")
                        .HasColumnName("group");

                    b.Property<bool?>("Spent")
                        .HasColumnType("bit")
                        .HasColumnName("spent");

                    b.Property<short>("Teacher")
                        .HasColumnType("smallint")
                        .HasColumnName("teacher");

                    b.Property<TimeOnly?>("Time")
                        .HasPrecision(0)
                        .HasColumnType("time(0)")
                        .HasColumnName("time");

                    b.HasKey("LessonId");

                    b.HasIndex("Discipline");

                    b.HasIndex("Group");

                    b.HasIndex("Teacher");

                    b.ToTable("Schedule", null, t =>
                        {
                            t.HasTrigger("Trg_AfterScheduleUpdate_InsertCompleteDisciplines");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Student", b =>
                {
                    b.Property<int>("StudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stud_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int?>("Group")
                        .HasColumnType("int")
                        .HasColumnName("group");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .HasColumnName("phone")
                        .IsFixedLength();

                    b.Property<byte[]>("Photo")
                        .HasColumnType("image")
                        .HasColumnName("photo");

                    b.HasKey("StudId");

                    b.HasIndex("Group");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Teacher", b =>
                {
                    b.Property<short>("TeacherId")
                        .HasColumnType("smallint")
                        .HasColumnName("teacher_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .HasColumnName("phone")
                        .IsFixedLength();

                    b.Property<byte[]>("Photo")
                        .HasColumnType("image")
                        .HasColumnName("photo");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("smallmoney")
                        .HasColumnName("rate");

                    b.Property<DateOnly?>("WorkSince")
                        .HasColumnType("date")
                        .HasColumnName("work_since");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("RequiredDiscipline", b =>
                {
                    b.Property<short>("Discipline")
                        .HasColumnType("smallint")
                        .HasColumnName("discipline");

                    b.Property<short>("RequiredDiscipline1")
                        .HasColumnType("smallint")
                        .HasColumnName("required_discipline");

                    b.HasKey("Discipline", "RequiredDiscipline1");

                    b.HasIndex("RequiredDiscipline1");

                    b.ToTable("RequiredDisciplines", (string)null);
                });

            modelBuilder.Entity("TeachersDisciplinesRelation", b =>
                {
                    b.Property<short>("Teacher")
                        .HasColumnType("smallint")
                        .HasColumnName("teacher");

                    b.Property<short>("Discipline")
                        .HasColumnType("smallint")
                        .HasColumnName("discipline");

                    b.HasKey("Teacher", "Discipline");

                    b.HasIndex("Discipline");

                    b.ToTable("TeachersDisciplinesRelation", (string)null);
                });

            modelBuilder.Entity("CompleteDiscipline", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("Discipline")
                        .IsRequired()
                        .HasConstraintName("FK_CompleteDisciplines_Disciplines");

                    b.HasOne("HW_Academy_CRUD.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("Group")
                        .IsRequired()
                        .HasConstraintName("FK_CompleteDisciplines_Groups");
                });

            modelBuilder.Entity("DependentDiscipline", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("DependentDiscipline1")
                        .IsRequired()
                        .HasConstraintName("FK_DependentDisciplines_Disciplines1");

                    b.HasOne("HW_Academy_CRUD.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("Discipline")
                        .IsRequired()
                        .HasConstraintName("FK_DependentDisciplines_Disciplines");
                });

            modelBuilder.Entity("DisciplinesDirectionsRelation", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Direction", null)
                        .WithMany()
                        .HasForeignKey("Direction")
                        .IsRequired()
                        .HasConstraintName("FK_DisciplinesDirectionsRelation_Directions");

                    b.HasOne("HW_Academy_CRUD.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("Discipline")
                        .IsRequired()
                        .HasConstraintName("FK_DisciplinesDirectionsRelation_Disciplines");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Attendance", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Schedule", "LessonNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("Lesson")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Schedule");

                    b.HasOne("HW_Academy_CRUD.Models.Student", "StudentNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("Student")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Students");

                    b.Navigation("LessonNavigation");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.DaysOff", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Holiday", "HolidayNavigation")
                        .WithMany("DaysOffs")
                        .HasForeignKey("Holiday")
                        .IsRequired()
                        .HasConstraintName("FK_DaysOFF_to_Holidays");

                    b.Navigation("HolidayNavigation");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Exam", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Discipline", "DisciplineNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("Discipline")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Disciplines");

                    b.HasOne("HW_Academy_CRUD.Models.Student", "StudentNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("Student")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Students");

                    b.Navigation("DisciplineNavigation");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Grade", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Schedule", "LessonNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("Lesson")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Schedule");

                    b.HasOne("HW_Academy_CRUD.Models.Student", "StudentNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("Student")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Students");

                    b.Navigation("LessonNavigation");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Group", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Direction", "DirectionNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("Direction")
                        .HasConstraintName("FK_Groups_Directions");

                    b.Navigation("DirectionNavigation");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Schedule", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Discipline", "DisciplineNavigation")
                        .WithMany("Schedules")
                        .HasForeignKey("Discipline")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Disciplines");

                    b.HasOne("HW_Academy_CRUD.Models.Group", "GroupNavigation")
                        .WithMany("Schedules")
                        .HasForeignKey("Group")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Groups");

                    b.HasOne("HW_Academy_CRUD.Models.Teacher", "TeacherNavigation")
                        .WithMany("Schedules")
                        .HasForeignKey("Teacher")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Teachers");

                    b.Navigation("DisciplineNavigation");

                    b.Navigation("GroupNavigation");

                    b.Navigation("TeacherNavigation");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Student", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Group", "GroupNavigation")
                        .WithMany("Students")
                        .HasForeignKey("Group")
                        .HasConstraintName("FK_Students_Groups");

                    b.Navigation("GroupNavigation");
                });

            modelBuilder.Entity("RequiredDiscipline", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("Discipline")
                        .IsRequired()
                        .HasConstraintName("FK_RequiredDisciplines_Disciplines");

                    b.HasOne("HW_Academy_CRUD.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("RequiredDiscipline1")
                        .IsRequired()
                        .HasConstraintName("FK_RequiredDisciplines_Disciplines1");
                });

            modelBuilder.Entity("TeachersDisciplinesRelation", b =>
                {
                    b.HasOne("HW_Academy_CRUD.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("Discipline")
                        .IsRequired()
                        .HasConstraintName("FK_TeachersDisciplinesRelation_Disciplines");

                    b.HasOne("HW_Academy_CRUD.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("Teacher")
                        .IsRequired()
                        .HasConstraintName("FK_TeachersDisciplinesRelation_Teachers");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Direction", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Discipline", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Group", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Holiday", b =>
                {
                    b.Navigation("DaysOffs");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Schedule", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Exams");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("HW_Academy_CRUD.Models.Teacher", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
